apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-vs-fluxcd
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: argocd-vs-fluxcd
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'