apiVersion: v2
name: argocd-vs-fluxcd-application
description: A Helm chart for sample application deployed with Argo or Flex CD
type: application
version: 1.0.0
appVersion: "0.0.1"

dependencies:
  - name: redis
    version: 15.3.0
    repository: https://charts.bitnami.com/bitnami
