image:
  repository: 100.125.7.25:20202/images/argocd-vs-fluxcd-application
  tag: 1.7

imageCredentials:
  registry: 100.125.7.25:20202
  username: eu-de_argocd-vs-fluxcd@H5U55ZJMUA8OYDXDY13D
  password: 063030b690a8b9ace326a3c5bdebb89762f5fd4a19423a27f2ed5fac8424137d
  email: someone@host.com

replicas: 1

redisUrl: "argocd-vs-fluxcd-redis-master:6379"

redis:
  global:
    storageClass: "csi-disk"
