image:
  name: docker.io/davidmilet/cicd
  tag: argocd-vs-fluxcd-application_0.0.1

imageCredentials:
  registry: docker.io
  username: davidmilet
  password: 21939803-844b-49d5-ab74-e23e34c48dbe
  email: david.milet@gmail.com

replicas: 1

redisUrl: "argocd-vs-fluxcd-redis-master:6379"

redis:
  global:
    storageClass: "standard"
  auth:
    enabled: false
  replica:
    replicaCount: 1
