apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: image-update
  namespace: flux-app-staging
spec:
  interval: 10m0s
  dependsOn:
    - name: app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/image-update/staging
  prune: true
  validation: client
