name: Production Auto-PR
on:
  push:
    branches:
      - production-update

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Update production ${{ github.ref }}"
          pr_body: "FluxCD proposes to update production infrastructure"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
